### ISSUE TITLE
wget 404

### ISSUE THREAD

**Issue by lesywix** [anjia0532/elastalert-wechat-plugin#6]
使用这条命令时出现404错误
wget -P ~/elastalert/elastalert_modules/ https://raw.githubusercontent.com/anjia0532/elastalert-wechat-plugin/master/wechat_qiye_alert.py

**Comment by anjia0532** [comment]
路径变了，博客忘了更新，你改一下就行 发自网易邮箱大师 在2017年10月21日 18:27，林炜翔 写道： 使用这条命令时出现404错误 wget -P ~/elastalert/elastalert_modules/ https://raw.githubusercontent.com/anjia0532/elastalert-wechat-plugin/master/wechat_qiye_alert.py — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by anjia0532** [comment]
@weixianglin `wget https://raw.githubusercontent.com/anjia0532/elastalert-wechat-plugin/master/elastalert_modules/wechat_qiye_alert.py`
